language: python
python:
   "2.7.13"
before_install:
   - pip install pytest pytest-cov
   - pip install coveralls
install:
     - pip install -r requirements.txt
script:
    - "pytest --cov=app app_tests.py"
after_success:
    - "coveralls"
